### ISSUE TITLE
Tests are failing while installation

### ISSUE THREAD

**Issue by tushardave26** [moznion/p6-Log-Minimal#5]
Hello Author,

I am trying to install the module using Panda. Below is my command line:

`panda install Log::Minimal`

Unfortunately, during the installation, one to many tests are failing. I have attached the panda log for your reference. Can you please help me to fix the issue?

Thanks.

Best,
Tushar
[panda_log.docx](https://github.com/moznion/p6-Log-Minimal/files/453111/panda_log.docx)

**Comment by moznion** [comment]
Thank you for your reporting. I'm sorry for my late reply.

This problem is probably fixed by

- https://github.com/moznion/p6-Log-Minimal/pull/4
- https://github.com/moznion/p6-Log-Minimal/pull/6
- 11da23b7f063809d4ac0d1b9c4db0b9eb9f368f4

**Comment by tushardave26** [comment]
Hello Moznion,

Thanks for your reply. Yes, the problem is fixed now. You can close the issue.

Best,
Tushar
